version: "3"

services:

  bakerydb:
    container_name: bakery_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: Password@123
    volumes:
      - ../BakeryTests/20240401.04.54.15.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  blazor:
   container_name: bakery_blazor
   depends_on:
     - bakerydb
   build: ..
   environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - db=Server=bakerydb;Database=postgres;Port=5432;User ID=postgres;Password=Password@123
     - Authentication:Google:ClientId="1042263982950-qq84p1l37u3jqrr8rcqj7n0u53b25832.apps.googleusercontent.com"
     - Authentication:Google:ClientSecret="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"
   ports:
     - "4765:8080"
#    healthcheck:
#       test: curl --fail http://localhost:4765/health || exit 1
#       interval: 60s
#       retries: 5
#       start_period: 20s
#       timeout: 10s
