scrape_configs:
    - job_name: prometheus
      scrape_interval: 5s
      static_configs:
        - targets:
          - kakey1-prometheus-service:9090
    - job_name: 'blackbox'
      scrape_interval: 5s
      metrics_path: /probe
      params:
        module: [http_2xx]
      static_configs:
        - targets:
          - http://kakey1-web-service:8080/health 
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: kakey1-blackbox-exporter:9115
    - job_name: 'metrics-blazor'
      scrape_interval: 5s 
      static_configs:
        - targets: ['kakey1-web-service:80']