receivers:
    otlp:
      protocols:
        grpc:
        http:
  
  exporters:
    # prometheus:
    #   endpoint: "0.0.0.0:1234"
    loki:
      endpoint: http://carlos-loki-service:3100/loki/api/v1/push
    # zipkin:
    #   endpoint: http://carlos_zipkin:9411/api/v2/spans
  
  extensions:
    health_check:     
  
  processors:
    batch:
  
  service:
    # extensions: [health_check] 
    pipelines:
    #   traces:
    #     receivers: [otlp]
    #     processors: [batch]
    #     exporters: [zipkin]
    #   metrics:
    #     receivers: [otlp]
    #     processors: []
    #     exporters: [prometheus]
      logs:
        receivers: [otlp]
        processors: [batch]
        exporters: [loki]