{
 "title": "Test dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Current Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"blackbox\", __name__=\"up\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime (Last 24 hours)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"blackbox\", __name__=\"up\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of visits per page (Last 24 hours)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{otel_scope_name=\"bakery.PopularPages\", __name__!=\"otel_scope_info\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average loading times for pages (Last 24 hours)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg by(__name__)({otel_scope_name=\"bakery.ProcessingTime\", __name__!=\"otel_scope_info\", __name__=~\".*bucket.*\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Social Media Buttons Interactions (Last 24 hours)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{otel_scope_name=\"bakery.SocialMedia\", __name__!=\"otel_scope_info\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completed Purchases (Last 24 hours)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{otel_scope_name=\"bakery.CompletedPurchases\", __name__!=\"otel_scope_info\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Access to Menu Page",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{job=\"bakery service\"} |~ \"User 'User-is-in-MenuPage'\"\r\n"
    }
   ]
  },
  {
   "title": "Error count (Last 24 hours)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "count_over_time({job=\"bakery service\", level=\"ERROR\"}[24h])\r\n"
    }
   ]
  },
  {
   "title": "Error Messages",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{job=\"bakery service\", level=\"ERROR\"} | json "
    }
   ]
  }
 ]
}