apiVersion: v1
kind: Service
metadata:
  labels:
    app: kakey1-blackbox-exporter
  name: kakey1-blackbox-exporter
  namespace: kakey1
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  selector:
    app: kakey1-blackbox-exporter
  ports:
  - port: 9115
    targetPort: 9115
    