apiVersion: apps/v1
kind: Deployment
metadata:
  name: kakey1-blackbox-deployment
  namespace: kakey1
  labels:
    app: kakey1-blackbox-exporter
spec:
  selector:
    matchLabels:
      app: kakey1-blackbox-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: kakey1-blackbox-exporter
    spec:
      restartPolicy: Always
      containers:
      - name: kakey1-blackbox-exporter
        image: prom/blackbox-exporter:v0.23.0
        ports:
        - containerPort: 9115
        volumeMounts:
        - name: config
          mountPath: /etc/blackbox/blackbox.yml
          subPath: kakey1-blackbox-config.yml  

      volumes:
      - name: config
        configMap:
          name: kakey1-blackbox-config
