apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: kakey1
  name: kakey1-web-ingress
  annotations:    
    cert-manager.io/cluster-issuer: cert-manager-webhook-duckdns-kakey1-production
spec:
  tls:
  - hosts:
    - kakey-kube.duckdns.org
    secretName: kakey-kube-tls-productio1n
  ingressClassName: nginx
  rules:
  - host: kakey-kube.duckdns.org 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kakey1-web-service
            port:
              number: 80
