apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kakey1
  name: kakey1-grafana-deployment
  labels:
    app: kakey1-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kakey1-grafana
  template:
    metadata:
      labels:
        app: kakey1-grafana
    spec:
      containers:
      - name: kakey1-grafana
        image: grafana/grafana:9.4.7
        ports:
        - containerPort: 3000
        env:
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "true"
        volumeMounts:
        - name: datasources
          mountPath: /etc/grafana/provisioning/datasources/datasource.yml
          subPath: bakery-datasource.yml
        - name: dashboard
          mountPath: /etc/grafana/provisioning/dashboards/dashboards.yml
          subPath: bakery-dashboard.yml
        - name: dashboard_contents
          mountPath: /etc/grafana/provisioning/dashboards/contents.json
          subPath: bakery-dashboard-content.json

      volumes:
      - name: datasources
        configMap:
          name: kakey1-grafana-datasource-config
      - name: dashboard
        configMap:
          name: kakey1-grafana-dashboard-config
      - name: dashboard_contents
        configMap:
          name: kakey1-grafana-dashboard-json
