apiVersion: v1
kind: Service
metadata:
  namespace: kakey1
  name: kakey1-collector-service
spec:
  type: ClusterIP
  selector:
    app: kakey1-collector
  ports:
    - port: 4317
      targetPort: 4317