name: backup database
on:
  workflow_dispatch
jobs:
  backup:
    runs-on: self-hosted
    steps:
      - name: backup
        run: |
          CONTAINER_NAME=$(kubectl -n kakey1 get pods --no-headers -o custom-columns=":metadata.name" | grep "blazor-web-db-deployment")
          kubectl -n kakey1 exec -t $CONTAINER_NAME -- \
            pg_dumpall -c -U postgres \
            > /home/ahmad/dump.sql
          cat /home/ahmad/dump.sql | kubectl exec -i $CONTAINER_NAME psql -U postgres


 