name: kakeyProcess
on:
  push:
jobs:
  DeployingPipeline:
    runs-on: kakeylabel
    env:
      Authentication_Google_ClientId: "1042263982950-qq84p1l37u3jqrr8rcqj7n0u53b25832.apps.googleusercontent.com"
      Authentication_Google_ClientSecret: "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"
      db: "host=postgresbakery.postgres.database.azure.com;user id=bakeryadmin;database=postgres;password=Password@123;"
    steps:
      - uses: actions/checkout@v4
      - name: "run integration tests"
        run: |
          cd ./BakeryTests/
          dotnet test
      # - name: "run unit tests"
      #   run: |
      #     cd ./Bakery.XUnitTests/
      #     dotnet workload restore [/home/ahmad/actions-runner-kakey/_work/bakery/bakery/Bakery.Mobile/Bakery.Mobile.csproj::TargetFramework=net8.0]
      #     dotnet test 
      # - name: "run linting"
      #   run: |
      #     cd ./
      #     docker run --rm -v "$(pwd):/app" -w /app -e DOTNET_CLI_HOME="/tmp/dotnet" --user $(id -u):$(id -g) mcr.microsoft.com/dotnet/sdk:8.0 dotnet format --verify-no-changes --severity warn 
      - name: "build warnings fail"
        run: |
          cd ./
          docker run --rm -v "$(pwd):/app" -w /app/ -e DOTNET_CLI_HOME="/tmp/dotnet" --user $(id -u):$(id -g) mcr.microsoft.com/dotnet/sdk:8.0 dotnet build

      - name: deploy
        run: |                
          docker build -t 144.17.92.12:5000/kakey1/kakey1-web:2 .
          docker push 144.17.92.12:5000/kakey1/kakey1-web:2

          kubectl delete configmap blazor-web-postgres-init -n kakey1
          kubectl -n kakey1 create configmap blazor-web-postgres-init --from-file=init.sql

          cd kube-bakery-configs

          kubectl delete configmap kakey1-otel-config -n kakey1 || true
          kubectl -n kakey1 create configmap kakey1-otel-config --from-file=bakery-collector-config.yml

          kubectl delete configmap kakey1-grafana-datasource-config -n kakey1 || true
          kubectl -n kakey1 create configmap kakey1-grafana-datasource-config --from-file=bakery-datasource.yml
          cd ..

          kubectl apply -f kubeBakeryDeploy/

