name: kakeyProcess

on:
  push:

jobs:
  DeployingPipeline:
    runs-on: kakeylabel
    env:
      Authentication_Google_ClientId: "1042263982950-qq84p1l37u3jqrr8rcqj7n0u53b25832.apps.googleusercontent.com"
      Authentication_Google_ClientSecret: "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"
    steps:
      - uses: actions/checkout@v4
      
      - name: "run integration tests"
        run: |
          cd ./BakeryTests/
          dotnet test

      - name: "run unit tests"
        run: |
          cd ./Bakery.XUnitTests/
          dotnet test 

      - name: "compute code coverage"
        run: |
          cd ./BakeryTests/
          rm -r TestResults || true
          dotnet test --collect:"XPlat Code Coverage"
          COBERTURA_FILE=$(find . -type f -name "*.xml")
          python3 -m pip install pycobertura
          python3 -m pycobertura show --format html --output coverage.html $COBERTURA_FILE

      - name: "run linting"
        run: |
          cd ./Bakery.WebApp/
          dotnet format --verify-no-changes --severity warn 

      - name: "build warnings fail"
        run: |
          cd ./Bakery.WebApp/
          dotnet build

      - name: deploy
        run: |      
          # cd ./bakery
          docker build -t 144.17.92.12:5000/kakey1/kakey1-web:$GITHUB_RUN_ID .
          docker push 144.17.92.12:5000/kakey1/kakey1-web:$GITHUB_RUN_ID

          kubectl delete configmap blazor-web-postgres-init -n kakey1 || true
          kubectl -n kakey1 create configmap blazor-web-postgres-init --from-file=init.sql

          cd kube-bakery-configs

          kubectl delete configmap kakey1-otel-config -n kakey1 || true
          kubectl -n kakey1 create configmap kakey1-otel-config --from-file=bakery-collector-config.yml

          kubectl delete configmap kakey1-grafana-datasource-config -n kakey1 || true
          kubectl -n kakey1 create configmap kakey1-grafana-datasource-config --from-file=bakery-datasource.yml

          kubectl delete configmap kakey1-blackbox-config -n kakey1 || true
          kubectl -n kakey1 create configmap kakey1-blackbox-config --from-file=bakery-blackbox-config.yml

          kubectl delete configmap kakey1-prometheus-config -n kakey1 || true
          kubectl -n kakey1 create configmap kakey1-prometheus-config --from-file=bakery-prometheus-config.yml

          cd ..

          for folder in ./kubeBakeryDeploy/*; do
                for file in $folder/*; do
                        echo "envsubst applied to $file"
                done
          done

          #kubectl apply -f kubeBakeryDeploy/ --recursive

  Push_to_Teams:
    runs-on: kakeylabel
    steps:
      - uses: actions/checkout@v2
      # this is the new step
      - uses: dchourasia/ms-teams-notification@1.0 #  or "./" if in a local set-up
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.KAKEY1_WEBHOOK }}
